### ISSUE TITLE
Allow bats role to test local changes or a PR

### ISSUE THREAD

**Issue by ehelms** [theforeman/forklift#409]

**Comment by ekohl** [comment]
To test local changes you can use:
```yaml
vars:                        
  bats_forklift_dir: /vagrant
  bats_update_forklift: "no" 
```

If you don't use NFS then you do need to use ```vagrant rsync $box``` but it works quite well. I use it in https://github.com/theforeman/forklift/pull/406 as well.
