### ISSUE TITLE
[centos7-devel] Evaluation Error: Error while evaluating a Function Call, Could not find template 

### ISSUE THREAD

**Issue by rahulbajaj0509** [theforeman/forklift#463]
Steps followed : 
```
git clone https://github.com/theforeman/forklift.git
cd forklift
cp boxes.yaml.example boxes.yaml
sed -i "s/<REPLACE ME>/rahulbajaj0509/g" boxes.yaml
vagrant up centos7-devel
```
Suspected error: (but not sure if this is the actual error)
https://paste.fedoraproject.org/paste/WFSOZ47SXkZauEqB3qNWkV5M1UNdIGYhyRLivL9gydE=

Complete log file:
[/var/log/foreman-installer/katello-devel.log](https://github.com/theforeman/forklift/files/1048051/katello-devel.zip)

**Comment by ekohl** [comment]
I think https://github.com/Katello/puppet-katello_devel/pull/108 should solve this. Doing a test run now.

**Comment by rahulbajaj0509** [comment]
Hey @ekohl , i am new to this project. I am sorry but i am not clear about what i have to do to solve this issue.

**Comment by ekohl** [comment]
You can make the installer use the PR by adding a variable in boxes.yaml. Essentially add the last line of the following:
```yaml
centos7-devel:
  box: centos7
  ansible:
    playbook: 'playbooks/devel.yml'
    group: 'devel'
    variables:
      katello_devel_github_username: <REPLACE ME>
      foreman_installer_module_prs: "katello/katello_devel/108"
```

After the PR has been merged and made it into nightlies you should remove the variable again if you re-provision or you're stuck with older code.
