### ISSUE TITLE
instructions unclear on running robottelo

### ISSUE THREAD

**Issue by thomasmckay** [theforeman/forklift#743]
I have no idea from the docs how to run robottelo. I'd like instructions to include:
+ sample boxes section (variables, etc.)
+ description of available variables
+ details on how this is meant to run (is it a separate vm or meant to run on existing server?)
+ how to work with a devel environment
+ how to work with the robottelo tests themselves (ie. how do i add/mod a test and re-run?)

**Comment by akofink** [comment]
I agree the documentation/examples needs to be improved. For the record, though, here's how I've got it working.

A playbook I put in `user_playbooks` (I think we should go ahead and add this as a playbook to forklift):

```yml
---
- hosts: all
  become: true
  roles:
    - robottelo
```

In boxes, use a box you already have up (possibly add this to the example local boxes file?):

```yml
centos7-katello-3.7:
  box: centos7
  ansible:
    playbook: 'user_playbooks/robottelo.yml'
```

And run `vagrant provision centos7-katello-3.7`. An alternative is to copy the playbook in question and add the robottelo role to the end; however, that's not really as feasible with the generated release boxes.

All the possible options are found in `forklift/roles/robottelo/defaults/main.yml` like every other Ansible role, though this requires some prior knowledge of Ansible. I don't know the answer to your last point. :)
