### ISSUE TITLE
Document and/or improve having virtualbox as a provider choice

### ISSUE THREAD

**Issue by thomasmckay** [theforeman/forklift#836]
I see some docs[1] and other references to virtualbox in this repo but am not sure how to set the provider in my _boxes.yaml_ file. I'm hoping it's a simple config per-box and I'll PR to update the docs.

Pinging @bastilian @ehelms - Any pointers or examples?

[1] https://github.com/theforeman/forklift/blob/8b95b1a2d9cb78e2675025400b748344d23e14ea/docs/production.md#using-virtualbox-windows-os-x

**Comment by ekohl** [comment]
We don't set this in boxes. It's part of core vagrant and thus documented there: https://www.vagrantup.com/docs/providers/basic_usage.html#default-provider

**Comment by thomasmckay** [comment]
Thanks! I'll make small doc PR to note that (I see it is noted in the following libvirt section).

**Comment by thomasmckay** [comment]
Adding 'devel' to the box name got past the above error (as it was actually trying to override port 80 again).

The working configuration:
```
    - type: 'private_network'
      options:
        type: dhcp
        ip: 192.168.57.112
        name: 'vboxnet1'
        adapter: 2
```
or to actually set the ip address
```
    - type: 'private_network'
      options:
        type: static
        ip: 192.168.57.112
        name: 'vboxnet1'
        adapter: 2
```
